name: CI Jeux Videops

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Installation de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Installation des dépendances
        run: npm ci

      - name: Vérification du Linter (Qualité)
        run: npm run eslint:check

      - name: Tests Unitaires et Couverture
        run: npm run nyc:run

      - name: Génération de la Documentation
        run: npm run jsdoc

      - name: Tests Fonctionnels (Cypress)
        run: npm run cypress:test